newIssueWelcomeComment: >
  Thanks for opening your first issue in the Pocket Dashboard repo! Someone will circle back soon âš¡
newPRWelcomeComment: >
  Thanks for opening this pull request! Someone will review it soon ðŸ”
firstPRMergeComment: >
  Congrats on merging your first pull request! Pocket is proud of you â›“
